Simplify GridActions GUI
gridsuite/gridactions-app pull request #13
Opened 2020-11-19 09:13 UTC by med-hedi

Signed-off-by: Mohamed Hedi Khefacha <mohamed.hedi@rte-france.com>

2020-11-19 12:00 UTC, ChamseddineBhd reviewed
Other remarks : 
when i rename a list the script disappear but the save button is not disabled !

2020-11-19 12:00 UTC, ChamseddineBhd commented on src/utils/rest-api.js
> +export function renameListByName(oldNameList, newNameList) {
oldNameList -> oldName  (List is already in the function name)
newNameList -> newName

2020-11-19 12:00 UTC, ChamseddineBhd commented on src/translations/en.json
> +    "newNameList": "New name list"
New list name ?

2020-11-19 12:00 UTC, ChamseddineBhd commented on src/translations/en.json
> +    "contingencyListIsEmpty": "Contingency lists is empty",
are empty?

2020-11-19 12:00 UTC, ChamseddineBhd commented on src/components/contingency-list.js
> +        getAllContngencyLists();
getAllContngencyLists-> getAllContingencyLists

2020-11-19 12:00 UTC, ChamseddineBhd commented on src/components/contingency-list.js
>                  setFirstItemInList(data[0]);
data could be empty so data[0] -> error !

2020-11-19 12:19 UTC, geofjamg requested changes
Usually, when a rename dialog is open, it is filled with current name. Cout you do this too?
Also there is no UI feedback if we you a name already take by another list. Button should be disabled in this case.
Also why is cancel button enabled when the groovy code has not been modified? It should only be available when changed has been made but not yet saved.

2020-11-19 12:37 UTC, ChamseddineBhd commented
> Usually, when a rename dialog is open, it is filled with current name. Could you do this too?
> Also there is no UI feedback if we you a name already take by another list. Button should be disabled in this case.
> Also why is cancel button enabled when the groovy code has not been modified? It should only be available when changed has been made but not yet saved.

There's no feedback for list deletion !

2020-11-20 12:47 UTC, ChamseddineBhd approved these changes

2020-11-20 12:59 UTC, med-hedi commented
@geofjamg I have fixed all the returns, concerning the popup I prefer do it in a separate pull request

2020-11-23 13:42 UTC, merged