display short version
gridsuite/gridactions-app pull request #29
Opened 2021-01-07 15:06 UTC by med-hedi

Signed-off-by: Mohamed Hedi Khefacha <mohamed.hedi@rte-france.com>

2021-01-27 20:17 UTC, geofjamg requested changes

2021-01-27 20:17 UTC, geofjamg commented on src/components/contingency-list.js
> +        backgroundColor: theme.palette.type === 'dark' ? '#404040' : '#f0f0f0',
Same remark as for gridstudy

2021-03-02 13:20 UTC, FranckLecuyer commented on src/components/contingency-list.js
> +        backgroundColor: theme.palette.type === 'dark' ? '#404040' : '#f0f0f0',
Corrected

2021-03-04 09:17 UTC, FranckLecuyer approved these changes

2021-03-10 17:54 UTC, jonenst approved these changes

2021-03-10 21:08 UTC, geofjamg approved these changes

2021-03-10 21:09 UTC, merged