Convert filters list to groovy script list
gridsuite/gridactions-app pull request #32
Opened 2021-02-25 12:58 UTC by FranckLecuyer

2021-03-04 09:16 UTC, FranckLecuyer commented
to be merged after PR: https://github.com/gridsuite/gridactions-app/pull/30

2021-03-10 16:59 UTC, geofjamg requested changes

2021-03-10 16:59 UTC, geofjamg commented on src/utils/rest-api.js
> +        body: JSON.stringify({
Why not just give the name of the filter list, everything is available in the DB?

2021-03-10 16:59 UTC, geofjamg commented on src/utils/rest-api.js
> +        body: JSON.stringify({
Same

2021-03-11 08:19 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +        body: JSON.stringify({
I dit it that way at first, to handle both cases (filter list with or without modifications in progress), but with the recent refactoring of code done in gridactions, the 2 methods 'replaceFiltersWithScriptContingencyList' and 'newScriptFromFiltersContingencyList' should effectively now use 'newFiltersContingency' state as argument, and not 'currentFiltersContingency'

So, can i just do that modification ?

2021-03-11 09:08 UTC, geofjamg commented on src/utils/rest-api.js
> +        body: JSON.stringify({
We should allow to create the script only from saved/validated filter list so, we can do it just with server data.

2021-03-11 12:24 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +        body: JSON.stringify({
Si, i have to make another PR in actions-server to do that

2021-03-11 13:36 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +        body: JSON.stringify({
Done

2021-03-11 13:36 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +        body: JSON.stringify({
Done

2021-03-12 12:59 UTC, geofjamg approved these changes

2021-03-12 12:59 UTC, merged