Add filter to griddata
gridsuite/gridactions-app pull request #43
Opened 2021-04-29 14:04 UTC by JacquesBorsenberger

2021-05-03 14:08 UTC, FranckLecuyer requested changes

2021-05-03 14:08 UTC, FranckLecuyer commented on src/utils/rest-api.js
> + * Get all contingency lists
Change comment

2021-05-03 14:08 UTC, FranckLecuyer commented on src/utils/rest-api.js
> + * Delete contingency list by name
Change comment

2021-05-03 14:08 UTC, FranckLecuyer commented on src/utils/rest-api.js
> + * Get contingency list by type
Change comment

2021-05-03 14:08 UTC, FranckLecuyer commented on src/utils/rest-api.js
> + * Rename list by name
Change comment

2021-05-03 14:08 UTC, FranckLecuyer commented on src/translations/en.json
> -    "LINE": "LINE",
"LINE" should remain

2021-05-03 14:08 UTC, FranckLecuyer commented on src/translations/fr.json
>      "addNewContencyFile": "Nom de la nouvelle liste",
Coherence problems between french and english json files
Ex : "Min", "Max"  <---> "MinNominalVoltage", "MaxNominalVoltage"

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/data-tabs.js
> +                <FilterList FilterRenderer={GenericFilter} listType={'line'} />
unused props

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/contingency-list.js
> +const ContingencyLists = ({ listType, FilterRenderer }) => {
Don't know the utility of these props

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/contingency-list.js
> +                    getContingencyLists(listType).then((data) => {
getContingencyLists has no argument

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/filter-list.js
> + * Copyright (c) 2020, RTE (http://www.rte-france.com)
2021

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/data-tabs.js
> +import React, { useState } from 'react';
Missing copyright

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/generic-filter.js
> +import { FormattedMessage } from 'react-intl';
Missing copyright

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/filters.js
> +import React, { useRef, useState } from 'react';
Missing copyright

2021-05-03 14:08 UTC, FranckLecuyer commented on src/components/custom-list-item.js
> +import { ScriptTypes } from '../utils/script-types';
Missing copyright

2021-05-04 10:55 UTC, FranckLecuyer commented
When we change nominal voltage filter from 'range' or 'approx' to 'equality', the 'value2' field remains unchanged in the sql table 'numericfilter', while it should be deleted

2021-05-04 10:59 UTC, FranckLecuyer commented
Labels 'equality', 'range', 'approx' are not aligned with the combobox arrow

2021-05-04 11:07 UTC, FranckLecuyer requested changes

2021-05-04 11:07 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "substationName": "Nom Poste",
If it is 'substationName, french translation should be 'Nom Site'
If it is 'Nom Poste', the english translation should be 'VoltageLevel Name' and the key renamed

2021-05-07 09:27 UTC, FranckLecuyer approved these changes

2021-05-12 13:25 UTC, niconoir requested changes
Contingency list and filter list are implemented in quite different ways, but they look and behave quite the same way. Maybe it would be useful to refactor contingency-list component to make its implementation closer to the filter-list component implementation. This would avoid some bugs like the look of the "New filter" and "New list" button which should be the same but actually look different.

2021-05-12 13:25 UTC, niconoir commented on src/components/filter-list.js
> +                    <FormattedMessage id="alertBeforeDeleteFilter" />
Message translation alertBeforeDeleteFilter is not present in translations files (fr.json and en.json)

2021-05-12 13:25 UTC, niconoir commented on src/translations/en.json
> +    "deleteFilter": "Delete filter"
Missing "alertBeforeDeleteFilter" translation

2021-05-12 13:25 UTC, niconoir commented on src/translations/fr.json
> +    "range": "interval"
Missing "alertBeforeDeleteFilter" translation

2021-05-12 13:25 UTC, niconoir commented on src/redux/actions.js
> +    console.info(filterList);
Is this console logging necessary ?

2021-05-12 13:25 UTC, niconoir commented on src/components/filter-list.js
> +            transient: true,
Why create the filter as transient ? It makes the creation behaviour different from contingency creation.

2021-05-12 13:25 UTC, niconoir commented on src/components/filter-list.js
> +                    className={classes.addNewList}
Here, the button style is quite different from the style used for new list creation in contingency-list. They should be identical, for the contingency list and filter list to look identical (right now, the buttons icons and labels sizes are different).

2021-05-12 13:25 UTC, niconoir commented on src/components/filters.js
> +        );
The language which is used for countries names localization should be retrieved in the application parameters, it is not necessarily the language of the navigator.

2021-05-12 13:25 UTC, niconoir commented on src/components/generic-filter.js
> +            direction="row"
Why "row" and not "column" ?

2021-05-12 13:25 UTC, niconoir commented on src/components/generic-filter.js
> +                            ].map((n) => {
The problem with this way to generate filters components is that it creates multiple filters with exactly the same label, and thus, we don't exactly know what the filter is used for (i.e. we can have two "countries" filters, and we don't exactly know what they really do)

2021-05-20 13:06 UTC, JacquesBorsenberger commented on src/components/filter-list.js
> +                    className={classes.addNewList}
need a whole US to refactor the contingency list

2021-05-26 10:25 UTC, JacquesBorsenberger commented on src/components/filters.js
> +        );
done

2021-05-26 10:27 UTC, JacquesBorsenberger commented on src/components/generic-filter.js
> +            direction="row"
removed

2021-05-28 14:40 UTC, niconoir approved these changes

2021-06-18 13:16 UTC, merged