Fix filter
gridsuite/gridactions-app pull request #45
Opened 2021-06-23 07:17 UTC by JacquesBorsenberger

2021-07-01 15:12 UTC, FranckLecuyer requested changes

2021-07-01 15:12 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function deleteFilterById(name) {
Maybe change the parameter 'name' into 'id' ?

2021-07-01 15:12 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function getFilterById(name) {
Same as above

2021-07-01 15:12 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function renameFilter(oldName, newName) {
Maybe rename parameter 'oldName' to 'oldId' ?

2021-07-02 11:50 UTC, niconoir requested changes

2021-07-02 11:50 UTC, niconoir commented on src/components/filter-list.js
> +        save(name);
Parameter name not needed

2021-07-02 11:54 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function deleteFilterById(name) {
Maybe change also function comment 'Delete filter by name' ?

2021-07-02 11:54 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function getFilterById(name) {
Same as above

2021-07-02 11:55 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function renameFilter(oldName, newName) {
Maybe change also function description 'Rename filter by name' ?

2021-07-02 11:58 UTC, FranckLecuyer reviewed
See my new remarks on functions descriptions in rest-api.js

2021-07-02 12:17 UTC, niconoir approved these changes

2021-07-02 12:27 UTC, JacquesBorsenberger commented on src/utils/rest-api.js
> +export function renameFilter(oldName, newName) {
done

2021-07-02 12:28 UTC, JacquesBorsenberger commented on src/utils/rest-api.js
> +export function getFilterById(name) {
done

2021-07-02 12:28 UTC, JacquesBorsenberger commented on src/utils/rest-api.js
> +export function deleteFilterById(name) {
done

2021-07-02 13:00 UTC, FranckLecuyer approved these changes

2021-07-02 13:08 UTC, merged